App\Entity\Product:
  properties:
    name:
      - NotBlank: ~
    created_at:
      - NotBlank: ~
    description:
      - NotBlank: ~
    price:
      - Type: integer
      - NotBlank: ~
    sku:
      - NotBlank: ~